# usb-c ed97e4
# MAC ..:..:..:ED:97:E4
# 08:D1:F9 ED97E4
substitutions:
  device_name: esp32-c-ed97e4
  domain: !secret DOMAIN

<<: !include include.lcd-touch.yaml

esphome:
  name: esp32-c-ed97e4

esp32:
  board: esp32dev
  # board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0 # disable sending to first uart device
  logs:
    component: ERROR

# generic services
time:
  - platform: sntp
    timezone: "Europe/Warsaw"
    id: sntp_time
    servers:
      - bagno
      - bagno.${domain}
      - pl.pool.ntp.org

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: ""
  # reboot_timeout: 0s # disable reboot if not connected to HA

ota:
  platform: esphome
  password: ""

wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD
  # use_address: 192.168.1.57

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: !secret WIFI_AP_PASSWORD

captive_portal:

# web ui info
text_sensor:
  - platform: version
    name: "ESPHome Version ${device_name}"

  - platform: wifi_info
    ip_address:
      name: "IP Address ${device_name}"
    ssid:
      name: "Connected SSID ${device_name}"
    bssid:
      name: "Connected BSSID ${device_name}"
    mac_address:
      name: "Mac Wifi Address ${device_name}"

  - platform: version
    name: "ESPHome Version ${device_name}"

button:
  - platform: restart
    name: "${device_name} Restart"

i2c:
  sda: GPIO21
  scl: GPIO22

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23 # TX
  miso_pin: GPIO19 # RX

# TODO: fix pinout to avoid esphome warning about using strap pins, for now it works
output:
  - id: lcd_brightness
    platform: ledc
    pin: GPIO17

light:
  - platform: monochromatic
    id: backlight
    name: "LCD backlight"
    output: lcd_brightness
    initial_state:
      state: on
      brightness: 60%
    restore_mode: ALWAYS_ON

display:
  - platform: ili9xxx
    model: ST7789V
    color_order: rgb
    auto_clear_enabled: false
    update_interval: never
    id: touch_display
    cs_pin: GPIO5
    dc_pin: GPIO2
    reset_pin: GPIO4
    invert_colors: true
    dimensions:
      height: 320 # 320 works, 300 trimmed on top
      width: 240
    #show_test_card: true
    data_rate: 80MHz

touchscreen:
  platform: cst816
  id: touch_surface
  interrupt_pin: GPIO16
  reset_pin: GPIO15

  # TODO: fix if doing backlight based on air quality level
  on_touch:
    - script.stop: backlight_timer
    - script.execute: backlight_timer

  # on_release:
  #   - lvgl.page.next:

#This is the script for turn off the backlight after some seconds of inactivity
script:
  id: backlight_timer
  then:
    - light.turn_on:
        id: backlight
        brightness: 80%

    - delay: 20s
    - light.turn_on:
        id: backlight
        brightness: 40%

    - delay: 30s
    - light.turn_on:
        id: backlight
        brightness: 20%
