# usb-c ed97e4
# MAC ..:..:..:ED:97:E4
# 08:D1:F9 ED97E4
substitutions:
  device_name: esp32-c-ed97e4
  domain: !secret DOMAIN
  lvgl_buffer_size: 25%

<<: !include include.lcd-touch.yaml

esphome:
  name: esp32-c-ed97e4

esp32:
  board: esp32dev
  # board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0 # disable sending to first uart device
  logs:
    component: ERROR

# generic services
time:
  - platform: sntp
    timezone: "Europe/Warsaw"
    id: sntp_time
    servers:
      - bagno
      - bagno.${domain}
      - pl.pool.ntp.org

web_server:
  port: 80


ota:
  platform: esphome
  password: ""

wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD
  # use_address: 192.168.1.57

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: !secret WIFI_AP_PASSWORD

captive_portal:

# web ui info
text_sensor:
  - platform: version
    name: "ESPHome Version ${device_name}"

  - platform: wifi_info
    ip_address:
      name: "IP Address ${device_name}"
    ssid:
      name: "Connected SSID ${device_name}"
    bssid:
      name: "Connected BSSID ${device_name}"
    mac_address:
      name: "Mac Wifi Address ${device_name}"

  - platform: version
    name: "ESPHome Version ${device_name}"

button:
  - platform: restart
    name: "${device_name} Restart"

i2c:
  sda: GPIO21 # TP_SDA
  scl: GPIO22 # TP_SCL

spi:
  clk_pin: GPIO18 # LCD_CLK
  mosi_pin: GPIO23 # LCD_DIN
  # miso_pin: GPIO19 # MISO, do not connect to anything

# TODO: fix pinout to avoid esphome warning about using strap pins, for now it works
output:
  - id: lcd_brightness
    platform: ledc
    pin: GPIO17 # LCD_BL

light:
  - platform: monochromatic
    id: backlight
    name: "LCD backlight"
    output: lcd_brightness
    initial_state:
      state: on
      brightness: 60%
    restore_mode: ALWAYS_ON

display:
  - platform: ili9xxx
    model: ST7789V
    color_order: rgb
    auto_clear_enabled: false
    update_interval: never
    id: touch_display
    cs_pin: GPIO5 # LCD_CS
    dc_pin: GPIO2 # LCD_DC
    reset_pin: GPIO4 # LCD_RST
    invert_colors: true
    dimensions:
      height: 280
      width: 240
      offset_height: 20
    show_test_card: true
    data_rate: 80MHz

touchscreen:
  platform: cst816
  id: touch_surface
  interrupt_pin: GPIO16 # TP_IRQ
  reset_pin: GPIO15 # TP_RST
  touch_timeout: 1000ms # prevent touch event flood?

  on_release:
    - if:
        condition: lvgl.is_paused
        then:
          - lvgl.resume:
          - lvgl.widget.redraw:
    - globals.set:
        id: backlight_percent
        value: '80'
    - light.turn_on:
        id: backlight
        brightness: !lambda return (id(backlight_percent) / 100.0);


script:
  - id: display_reprocess
    then:
      - logger.log:
          format: "display_reprocess triggered: backlight_percent=%d"
          args: [ 'id(backlight_percent)' ]
      - if:
          condition:
            lambda: 'return id(backlight_percent) == 0;'
          then:
            - logger.log: lvgl paused
            - lvgl.pause: # stop updating display if brightness is off
            - light.turn_off:
                id: backlight
          else:
            - light.turn_on:
                id: backlight
                brightness: !lambda return (id(backlight_percent) / 100.0);
            - if:
                condition: lvgl.is_paused
                then:
                  - lvgl.resume:
                  - lvgl.widget.redraw:
