# ESP32 run on host using SDL, so all software
substitutions:
  device_name: esp32-host
  domain: !secret DOMAIN
  lvgl_buffer_size: 25%

<<: !include include.lcd-touch.yaml

esphome:
  name: sdl

# notice that host platform does not need wifi module, but it needs MAC address
host:
  mac_address: "06:35:69:ab:f6:79"

display:
  - platform: sdl
    auto_clear_enabled: false # required for sdl
    dimensions:
      height: 280
      width: 240
      # offset_height: 20
