# usb-c ed97e4
# # binary fan esperanza cyclone
# MAC ..:..:..:ED:97:E4
# 08:D1:F9 ED97E4
substitutions:
  device_name: esp32-host
  domain: !secret DOMAIN

<<: !include include.lcd-touch.yaml

esphome:
  name: sdl

# notice that host platform does not need wifi module
host:
  mac_address: "06:35:69:ab:f6:79"

display:
  - platform: sdl
    auto_clear_enabled: false # required fo sdl
    dimensions:
      height: 320 # 320 works, 300 trimmed on top
      width: 240
