---
site_name: "ESPHome 3D Printer Smart Enclosure"
site_url: "https://nvtkaszpir.github.io/esphome-3d-printer-smart-enclosure"
repo_url: "https://github.com/nvtkaszpir/esphome-3d-printer-smart-enclosure"

theme:
  name: material
  features:
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  palette:
    primary: black
  logo: static/logo.png

extra_css:
  - css/extra.css

plugins:
  - git-revision-date-localized:
      type: custom
      custom_format: "%Y-%m-%d %H:%M:%S %z (UTC)"
      timezone: Europe/Warsaw
  - search
  - mermaid2
  - tags

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - About: index.md
  - Why: why.md
  - Known Limitations: known_limitations.md
  - Architecture: architecture.md
  - Requirements: requirements.md
  - Features: featuers.md
  - To Do: todo.md
